FROM ubuntu:latest
RUN apt-get update -y 
RUN apt-get install -y python3.8
RUN apt install -y python3-pip
RUN pip install Spacy
RUN python3 -m spacy download en
RUN pip3 install boto3 --upgrade
RUN pip3 install awscli
RUN pip install boto3 --upgrade
RUN pip install awscli
RUN pip install PyPDF2
RUN pip install pdfminer
RUN pip install PyMuPDF
RUN pip3 install PyMuPDF
RUN pip3 install Flask
RUN pip install python-dotenv
RUN pip3 install python-dotenv